# List of exercises

<a href="Data/Data.zip" download target="_blank">Zip file with the needed data files</a>

- [Basics – data.frame manipulation, simple plots and linear fits](Exo/Rexercises-plot0.html) 
    - <a href="Exo/Rexercises-plot0_exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/Rexercises-plot0_solution.html) (only available after the correction is done in class)
- [Spectroscopic data: reading data, plotting and stacking curves](Exo/Rexercises-spectro.html) 
    - <a href="Exo/Rexercises-spectro_exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/Rexercises-spectro_solution.html) (only available after the correction is done in class)
- [TGA data: loading a complicated text file, derivative and plotting](Exo/Rexercises-tga.html) 
    - <a href="Exo/Rexercises-tga_exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/Rexercises-tga_solution.html) (only available after the correction is done in class)
- [CO2 emissions: data wrangling and ggplot2](Exo/Rexercises-co2.html) 
    - <a href="Exo/Rexercises-co2_exo.Rmd" download target="_blank">Rmd</a>
    - Solution (only available after the correction is done in class)
- [G(r,t): reading data from MD simulations treatments and plotting them](Exo/Rexercises-Grt.html) 
    - <a href="Exo/Rexercises-Grt_exo.Rmd" download target="_blank">Rmd</a>
    - Solution (only available after the correction is done in class)
- [Religion and babies: data wrangling, ggplot2 and plotly](Exo/Rexercises-religion_babies.html) 
    - <a href="Exo/Rexercises-religion_babies_exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/Rexercises-religion_babies_solution.html) (only available after the correction is done in class)
- [COVID-19: data wrangling, ggplot2, fits](Exo/Rexercises-covid.html) 
    - <a href="Exo/Rexercises-covid_exo.Rmd" download target="_blank">Rmd</a>
    - Solution (only available after the correction is done in class)





