# List of exercises


::: {.grid}


::: {.g-col-3}

<div class="tile">
**Basics**  
[Exercise](Exo/plot0/exercise.html) / [Solution](Exo/plot0/solution.html)  
`data.frame` manipulation, simple plots and linear fits   
</div>

:::

::: {.g-col-3}

<div class="tile">
**FTIR data**  
[Exercise](Exo/FTIR/exercise.html) / [Solution](Exo/FTIR/solution.html)  
Reading data, plotting curves   
</div>

:::

::: {.g-col-3}

<div class="tile">
**Spectroscopic data 1**  
[Exercise](Exo/spectro1/exercise.html) / [Solution](Exo/spectro1/solution.html)  
Reading data, plotting and stacking curves   
</div>

:::

::: {.g-col-3}

<div class="tile">
**Spectroscopic data 2**  
[Exercise](Exo/spectro2/exercise.html) / [Solution](Exo/spectro2/solution.html)  
Reading data, fitting, plotting and stacking curves   
</div>

:::

::: {.g-col-3}

<div class="tile">
**TGA data**  
[Exercise](Exo/tga/exercise.html) / [Solution](Exo/tga/solution.html)  
Loading a complicated text file, derivative and plotting   
</div>

:::

::: {.g-col-3}

<div class="tile">
**Peapods**  
[Exercise](Exo/peapods/exercise.html) / [Solution](Exo/peapods/solution.html)  
Reading data, fitting, plotting and stacking curves   
</div>

:::

::: {.g-col-3}

<div class="tile">
**CO2 emissions**  
[Exercise](Exo/co2/exercise.html) / [Solution](Exo/co2/solution.html)  
Data wrangling and `ggplot2`   
</div>

:::

::: {.g-col-3}

<div class="tile">
**Cognitive Psychology**  
[Exercise](Exo/psycho_cog/exercise.html) / [Solution](Exo/psycho_cog/solutin.html))  
Data wrangling and `ggplot2`   
</div>

:::

::: {.g-col-3}

<div class="tile">
**G(r,t)**  
[Exercise](Exo/Grt/exercise.html) / [Solution](Exo/Grt/solution.html)  
Reading data from MD simulations treatments and plotting them   
</div>

:::

::: {.g-col-3}

<div class="tile">
**Religion and babies**  
[Exercise](Exo/religion_babies/exercise.html) / [Solution](Exo/religion_babies/solution.html)  
Data wrangling, `ggplot2` and plotly   
</div>

:::

::: {.g-col-3}

<div class="tile">
**Bulk modulus**  
[Exercise](Exo/bulk_modulus/exercise.html) / [Solution](Exo/bulk_modulus/solution.html)  
Data wrangling, `ggplot2` and fitting   
</div>

:::

::: {.g-col-3}

<div class="tile">
**Nanoparticles statistics from SEM images**  
[Exercise](Exo/SEM_particles/exercise.html) / [Solution](Exo/SEM_particles/solution.html)  
Data wrangling, `ggplot2` and fitting   
</div>

:::

::: {.g-col-3}

<div class="tile">
**COVID-19**  
[Exercise](Exo/covid/exercise.html) / [Solution](Exo/covid/solution.html)  
Data wrangling, `ggplot2`, fits   
</div>

:::

:::
