# List of exercises

- [Basics – data.frame manipulation, simple plots and linear fits](Exo/plot0/exercise.html) 
    - <a href="Exo/plot0/exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/plot0/solution.html) (only available after the correction is done in class)
- [FTIR data: reading data, plotting curves](Exo/FTIR/exercise.html) 
    - <a href="Exo/FTIR/exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/FTIR/solution.html) (only available after the correction is done in class)
- [Spectroscopic data: reading data, plotting and stacking curves](Exo/spectro/exercise.html) 
    - <a href="Exo/spectro/exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/spectro/solution.html) (only available after the correction is done in class)
- [TGA data: loading a complicated text file, derivative and plotting](Exo/tga/exercise.html) 
    - <a href="Exo/tga/exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/tga/solution.html) (only available after the correction is done in class)
- [CO2 emissions: data wrangling and ggplot2](Exo/co2/exercise.html) 
    - <a href="Exo/co2/exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/co2/solution.html) (only available after the correction is done in class)
- [G(r,t): reading data from MD simulations treatments and plotting them](Exo/Grt/exercise.html) 
    - <a href="Exo/Grt/exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/Grt/solution.html) (only available after the correction is done in class)
- [Religion and babies: data wrangling, ggplot2 and plotly](Exo/religion_babies/exercise.html) 
    - <a href="Exo/religion_babies/exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/religion_babies/solution.html) (only available after the correction is done in class)
- [Nanoparticles statistics from SEM images: data wrangling, ggplot2 and fitting](Exo/SEM_particles/exercise.html) 
    - <a href="Exo/SEM_particles/exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/SEM_particles/solution.html) (only available after the correction is done in class)
- [COVID-19: data wrangling, ggplot2, fits](Exo/covid/exercise.html) 
    - <a href="Exo/covid/exo.Rmd" download target="_blank">Rmd</a>
    - [Solution](Exo/covid/solution.html) (only available after the correction is done in class)





