format:
  pdf:
    theme     : cosmo
    page-layout: full
    linkcolor : "#3d54cb"
    code-link : true
    code-line-numbers: false
    number-sections: true
    code-block-border-left: true
    code-block-bg: "#f6f4ef"
    highlight-style: atom-one
    engine: knitr

knitr:
  opts_chunk:
    comment: "#> "
    class-source : codeoutput
    width: 80

execute:
  cache     : false
  out-width : '75%'
  fig-asp   : .618034
  fig-align : center
  warning   : false
  message   : false