---
name: John
surname: Doe
date: "`r format(Sys.time(), '%B, %Y')`"
qualifications: PhD
position: Research Scientist
address: My Fancy Lab name
email: john.doe@cnrs.fr
website: https://johndoe.github.io/
github: johndoe
googlescholar: 123456
orcid: 0000-1111-2222-3333
phone: +1 22 33 44 55 66
headcolor: 414141 # for no headcolor
header-includes:
    - \definecolor{BLUE}{RGB}{64, 61, 141}
    - \hypersetup{colorlinks=true,linkcolor=BLUE,citecolor=BLUE,urlcolor=BLUE}
output: 
  vitae::awesomecv
---

```{r setup, include=FALSE}
library(tidyverse)
library(glue)
library(vitae)
library(httr)
knitr::opts_chunk$set(echo = FALSE)
bibfile <- "biblio.bib"
myname  <- "Doe"
```

# Professional Experience

```{r consulting}
tribble(
  ~ lab, ~ position, ~ city, ~ dates, ~ details,
  "My Fancy Lab name", "Research Scientist", "Lyon, France", "Oct. 2017 - Present", 
    list("I do this",
         "and that")
) %>% 
  detailed_entries(lab, dates, position, city, details)
```

# Education

```{r education}
tribble(
  ~ degree, ~ uni, ~ loc, ~ dates, ~ details,
  "BCom (Hons) in Econometrics", "Monash University", "Clayton, Australia", "Mar. 2017 - Nov. 2017", 
    list("Recipient of the Econometrics Honours Memorial Scholarship, Dean's Honour, Dean's Commendation, and best in class for 5 units.",
         "Honours research project was to develop a state space model for quickly forecasting time series with multiple seasonalities.",
         "Studied units include Bayesian and frequentist econometrics, advanced statistical modelling and computational science."),
  "BCom in Econometrics, BSc in Mathematical statistics and Computational Science", "Monash University", "Clayton, Australia", "Mar. 2013 - Nov. 2016", 
    list("Recipient of the Monash Community Leaders Scholarship, International Institute of Forecasters Award, and best in class for 4 units.",
         "Mentor for the Access Monash Ambassador Program (2015 and 2016)",
         "Participant of the Vice-Chancellor's Ancora Imparo Student Leadership Program (2014)",
         "Studied a broad range of units covering many aspects of data science. The three disciplines I majored in explored different perspectives for working with data.")
) %>% 
  detailed_entries(degree, dates, uni, loc, details)
```

# Teaching experience

## Teaching

Some blah blah

```{r tutoring}
tribble(
  ~ title, ~ code, ~ campus, ~ semester,
  "Applied forecasting", "ETC3550/ETC5550", "Clayton", "2021 S1",
  "Communicating with Data", "ETC5523", "Clayton", "2020 S2", 
  "Applied forecasting", "ETC3550/ETC5550", "Clayton", "2020 S1"
) %>% 
  brief_entries(glue::glue("\\textbf{<code>}: <title> (Monash <campus>)", .open = "<", .close = ">"), semester, .protect = FALSE)
```

## Student mentoring

Some blah blah

```{r mentoring}
tribble(
  ~ studentname, ~ level, ~ where, ~ year, ~what,
  "John", "M1", "University of Lyon", "2017", "internship on this and that",
  "Lisa", "PhD", "University of Boston", "2018-2021", NA
) %>% 
    arrange(desc(year)) %>% 
    mutate(toprint = glue::glue("\\textbf{<studentname>} (<level>)", .open = "<", .close = ">")) %>% 
    mutate(toprint = ifelse(!is.na(what), 
                            glue::glue("{toprint}: {what}"), 
                            toprint)) %>% 
    brief_entries(toprint, year, where, .protect = FALSE)
```


# Presentations at international conferences

```{r talks}
tribble(
  ~ when, ~ title, ~ details, ~ where, ~ url,
  "2020", "Forecasting with multiple seasonality", "Methods and techniques to multiple seasonal forecasting in R", "UK NHS", "https://slides.mitchelloharawild.com/nhs2020/",
  "2020", "Probabilistic cross-temporal hierarchies", NA, "ISF", "https://slides.mitchelloharawild.com/isf2020/",
  "2019", "Flexible futures for fable functionality", "Gradual introduction to tidy forecasting with fable. Flexibility is demonstrated with combination modelling and package extensibilitiy.", "MelbURN meetup", NA
) %>% 
    mutate(toprint = glue::glue("\\textbf{<title>}", .open = "<", .close = ">")) %>% 
    mutate(toprint = ifelse(!is.na(details), 
                            glue::glue("{toprint}: {details}"), 
                            toprint)) %>% 
    mutate(toprint = ifelse(!is.na(url), 
                            glue::glue("<toprint>\\newline \\url{<url>}", .open = "<", .close = ">"),
                            toprint)) %>% 
    brief_entries(toprint, when, where, .protect = FALSE)
```


# Awards & Achievements

```{r}
tribble(
  ~ award, ~ from, ~ year,
  "Commerce Dean's Honour", "Monash", "2017",
  "Commerce Dean's Commendation", "Monash", "2016",
  "Science Dean’s List", "Monash", "2014-2016",
  "International Institute of Forecasters Award", "IIF", "2014",
  "Rotary Youth Leadership Award", "Rotary", "2013"
) %>%
  brief_entries(award, year, from)
```


# Publications

```{r, warning=FALSE, message=FALSE}
reverse_names <- function(name="Amaral, I. R.") {
    name_list <- unlist(str_split(name, ", "))
    initial <- paste0(unlist(str_split(name_list[2], ""))[1],".")
    paste(initial, name_list[1])
}
parse_authors <- function(aut_list=pubs$AUTHOR[[1]], author=myname) {
    aut_list <- map_chr(aut_list, reverse_names)
    aut_list[grep(tolower(author), tolower(aut_list))] <- 
        paste0("\\textbf{", 
                aut_list[grep(tolower(author), tolower(aut_list))], 
                "}")
    aut_list <- unique(aut_list)
    aut_list <- paste(aut_list, collapse = ", ")
}
parse_journal <- function(JOURNAL, VOLUME, PAGES, YEAR) {
    out <- paste0(JOURNAL, " \\textbf{", VOLUME, "} (", YEAR, "), ", PAGES)
    out <- gsub(" \\\\textbf\\{NA\\}", "", out)
    gsub(", NA", "", out)
}
pubs <- bib2df::bib2df(bibfile) %>% 
    filter(str_detect(tolower(AUTHOR), tolower(myname)), 
           !is.na(DOI))  %>% 
    arrange(desc(YEAR)) %>% 
    select(TITLE, AUTHOR, YEAR, JOURNAL, VOLUME, PAGES, DOI) %>% 
    mutate(count = n()-row_number()+1,
           AUTHOR = map_chr(AUTHOR, parse_authors), 
           TITLE = glue("[<count>]~\\href{http://doi.org/<DOI>}{<TITLE>}", .open = "<", .close = ">"),
           JOURNAL = parse_journal(JOURNAL,VOLUME,PAGES,YEAR))
pubs %>%
    detailed_entries(
        what = AUTHOR,
        with = TITLE,
        where = JOURNAL,
        .protect = FALSE
    )
```

