---
title : "Title"
author: "Colin Bousige"
date  : "`r Sys.Date()`"
output: 
    html_document: 
        toc            : yes
        toc_float      : TRUE
        code_folding   : hide
        code_download  : TRUE
        highlight      : tango
        number_sections: true
params: 
    solution:
        value: false
---


```{r setup, include=FALSE, warning = FALSE, cache=FALSE}
library(plotly)
library(ggplot2)
library(tidyverse)
library(lubridate)
library(gganimate)
library(transformr)
theme_set(theme_bw()+theme(panel.border = element_blank()))
```

```{r include=TRUE, warning = FALSE, message=FALSE, cache=FALSE}
data_url <- "https://datahub.io/core/global-temp/r/monthly.csv"
data_raw <- read_csv(data_url)
dataT <- data_raw %>% group_by(Date) %>% 
    summarize(Temperature=mean(Mean)) %>% 
    mutate(month=month(Date),
           year=year(Date)
           )
colors <- colorRampPalette(c("royalblue","seagreen","lightblue","lightblue","#fff987","orange","red","brown"))(500)
# colors <- colorRampPalette(c("darkblue","royalblue","seagreen","#fff987","orange","red","brown","black"))(500)
P <- ggplot(dataT, aes(x=factor(month), y=Temperature, color=Temperature, group=year))+
    geom_hline(yintercept = 0, size=15, alpha=.8, color="darkgrey")+
    geom_polygon(fill=NA)+
    scale_colour_gradientn(colors=colors)+
    scale_x_discrete(labels=month(1:12, label=TRUE))+
    coord_polar()+
    theme(axis.title.x=element_blank(),
          axis.title.y=element_blank(),
          axis.text.y=element_blank(),
          axis.ticks.y=element_blank()
         )
    # Here comes the gganimate specific bits
P+transition_reveal(year)+
    ggtitle('Year: {as.integer(frame_time)}') +
    transition_time(year)+
    shadow_trail(distance = 0.01, alpha=.2)
```
